-- Generated by Oracle SQL Developer Data Modeler 4.0.3.853
--   at:        2015-05-10 14:27:48 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




CREATE TABLE AGENT
  (
    ID_Agenta    INTEGER NOT NULL ,
    Imie            VARCHAR (64) NOT NULL ,
    Nazwisko            VARCHAR(64) NOT NULL ,
    Adres               VARCHAR (64) NOT NULL ,
    Data_Urodzenia   DATE NOT NULL ,
    Data_Zatrudnienia DATE NOT NULL ,
    ID_Szefa          INTEGER ,	
    Pensja              INTEGER  NOT NULL ,
    Notatka             VARCHAR (64) ,
    ID_Regionu          INTEGER  NOT NULL
  ) ;
ALTER TABLE AGENT ADD CONSTRAINT AGENT_PK PRIMARY KEY (ID_Agenta) ;

CREATE TABLE KLIENT
  (
    Pesel_Klienta INTEGER  NOT NULL ,
    Imie          VARCHAR (64) NOT NULL ,
    Nazwisko      VARCHAR (64) NOT NULL ,
    Adres         VARCHAR (64) NOT NULL ,
    Miejscowosc   VARCHAR (64) NOT NULL ,
    Notatka       VARCHAR(64)
  ) ;
ALTER TABLE KLIENT ADD CONSTRAINT KLIENT_PK PRIMARY KEY ( Pesel_Klienta ) ;

CREATE TABLE REGION
  (
    Miejscowosc VARCHAR (64) NOT NULL ,
    ID_Regionu  INTEGER NOT NULL
  ) ;
ALTER TABLE REGION ADD CONSTRAINT REGION_PK PRIMARY KEY ( ID_Regionu ) ;

CREATE TABLE SPOTKANIA
  (
    Data_Spotkania DATE NOT NULL ,
    Uwagi          VARCHAR(64) ,
    Pesel_Klienta  INTEGER NOT NULL ,
    ID_Agenta    INTEGER NOT NULL ,
    ID_Regionu     INTEGER  NOT NULL
  ) ;

CREATE TABLE SZKOLENIA
  (
    Nazwa        VARCHAR (64) NOT NULL ,
    Data         DATE NOT NULL ,
    Ilosc_Miejsc INTEGER ,
    ID_Agenta    INTEGER ,
    Uwagi        VARCHAR (64) ,
    ID_Regionu INTEGER  NOT NULL
  ) ;
ALTER TABLE SZKOLENIA ADD CONSTRAINT SZKOLENIA_PK PRIMARY KEY ( Nazwa ) ;

CREATE TABLE TYP_UMOWY
  (
    Typ              INTEGER NOT NULL ,
    Czas_Trwania    INTEGER  NOT NULL ,
    Kwota            INTEGER  NOT NULL ,
    Notatka          VARCHAR (64) ,
    Max_Kwota        INTEGER  NOT NULL ,
    Min_Kwota        INTEGER NOT NULL ,
    Max_czas_trwania INTEGER NOT NULL ,
    Min_czas_trwania INTEGER NOT NULL
  ) ;
ALTER TABLE TYP_UMOWY ADD CONSTRAINT TYP_UMOWY_PK PRIMARY KEY ( Typ ) ;

CREATE TABLE UMOWY
  (
    Nr_Umowy         INTEGER NOT NULL ,
    Data_Zawarcia    DATE NOT NULL ,
    Data_Zakonczenia DATE NOT NULL ,
    Skladka          INTEGER NOT NULL ,
    ID_Agenta      INTEGER NOT NULL ,
    UMOWY_Typ       INTEGER NOT NULL ,
    Pesel_Klienta    INTEGER NOT NULL
   
  ) ;
ALTER TABLE UMOWY ADD CONSTRAINT UMOWY_PK PRIMARY KEY ( Nr_Umowy ) ;

ALTER TABLE AGENT ADD CONSTRAINT AGENT_REGION_FK FOREIGN KEY ( ID_Regionu ) REFERENCES REGION ( ID_Regionu ) ;

ALTER TABLE SPOTKANIA ADD CONSTRAINT SPOTKANIA_AGENT_FK FOREIGN KEY ( ID_Agenta ) REFERENCES AGENT ( ID_Agenta ) ;

ALTER TABLE SPOTKANIA ADD CONSTRAINT SPOTKANIA_KLIENT_FK FOREIGN KEY ( Pesel_Klienta ) REFERENCES KLIENT ( Pesel_Klienta ) ;

ALTER TABLE SPOTKANIA ADD CONSTRAINT SPOTKANIA_REGION_FK FOREIGN KEY ( ID_Regionu ) REFERENCES REGION ( ID_Regionu ) ;

ALTER TABLE SZKOLENIA ADD CONSTRAINT SZKOLENIA_REGION_FK FOREIGN KEY ( ID_Regionu ) REFERENCES REGION ( ID_Regionu ) ;

ALTER TABLE UMOWY ADD CONSTRAINT UMOWY_AGENT_FK FOREIGN KEY ( ID_Agenta ) REFERENCES AGENT ( ID_Agenta ) ;

ALTER TABLE UMOWY ADD CONSTRAINT UMOWY_KLIENT_FK FOREIGN KEY ( Pesel_Klienta ) REFERENCES KLIENT ( Pesel_Klienta ) ;

ALTER TABLE UMOWY ADD CONSTRAINT UMOWY_TYP_UMOWY_FK FOREIGN KEY ( UMOWY_Typ ) REFERENCES TYP_UMOWY ( Typ ) ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             14
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
